- name: using block
  hosts: all
  become: yes
  tasks:
    - block:
      - name: task1
        yum:
          name: httpd1234
          state: present

      rescue:
        - name: task2
          debug:
            msg: task resuced

      always:
        - name: task3
          debug:
            msg: this will always run

